########################################################################################################################
#                                                                                                                      #
#                                                      LINUX                                                           #
#                                                                                                                      #
########################################################################################################################
linux_builds_task:
  matrix:
    - name: "linux-dotnet-6.0-x64"
      container:
        image: mcr.microsoft.com/dotnet/runtime:6.0
    - name: "linux-dotnet-7.0-x64"
      container:
        image: mcr.microsoft.com/dotnet/runtime:7.0
    - name: "alpine-dotnet-6.0-x64"
      container:
        image: mcr.microsoft.com/dotnet/runtime:6.0-alpine
    - name: "alpine-dotnet-7.0-x64"
      container:
        image: mcr.microsoft.com/dotnet/runtime:7.0-alpine
    - name: "linux-dotnet-6.0-arm64"
      arm_container:
        image: mcr.microsoft.com/dotnet/runtime:6.0
    - name: "linux-dotnet-7.0-arm64"
      arm_container:
        image: mcr.microsoft.com/dotnet/runtime:7.0
    - name: "alpine-dotnet-6.0-arm64"
      arm_container:
        image: mcr.microsoft.com/dotnet/runtime:6.0-alpine
    - name: "alpine-dotnet-7.0-arm64"
      arm_container:
        image: mcr.microsoft.com/dotnet/runtime:7.0-alpine
  
  build_script:
    - dotnet build
  
  test_script:
    - dotnet test
